jobs:
  include:
    - stage: quicktest
      env: TASK=travis-format

    - stage: libraries
    - env: TASK=internal_model-test

script:
  >
    make "$TASK"
    if [[ "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_BUILD_STAGE_NAME" == "Services" ]]
    then
      make "${TASK/test/publish}"
    fi

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - target

    - internal_model/target

stages:
  - preflight
  - libraries
  - services

install:
  # We need this for the Elasticsearch Docker container to start
  # See https://github.com/travis-ci/travis-ci/issues/6534
  - sudo sysctl -w vm.max_map_count=262144

language: sh

services:
  - docker

dist: trusty

branches:
  only:
    - master

# Based on instructions from
# https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching
before_cache:
  - sudo find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - sudo find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
    - AWS_ECR_REPO=760097843905.dkr.ecr.eu-west-1.amazonaws.com

    # This forces Python to print everything to stdout/stderr immediately.
    # Otherwise, we've seen issues where all the output from our Travis scripts
    # gets buffered, and only gets printed at the end of the test...
    #
    # ... out of order from the rest of the rest of the output!
    #
    # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
    #
    - PYTHONUNBUFFERED=x
