jobs:
  include:
    - stage: preflight
      name: travis-format
      env: TASK=travis-format

    - stage: libraries
      name: internal_model
      script: ./.travis/run_job.py internal_model
    - name: display
      script: ./.travis/run_job.py display
    - name: elasticsearch
      script: ./.travis/run_job.py elasticsearch
    - name: big_messaging
      script: ./.travis/run_job.py big_messaging
    - name: ingestor_common
      script: ./.travis/run_job.py ingestor_common
    - name: transformer_common
      script: ./.travis/run_job.py transformer_common

    - stage: services
      name: api
      script: ./.travis/run_job.py api
    - name: reindex_worker
      script: ./.travis/run_job.py reindex_worker
    - name: id_minter
      script: ./.travis/run_job.py id_minter
    - name: ingestor_works
      script: ./.travis/run_job.py ingestor_works
    - name: ingestor_images
      script: ./.travis/run_job.py ingestor_images
    - name: matcher
      script: ./.travis/run_job.py matcher
    - name: merger
      script: ./.travis/run_job.py merger
    - name: recorder
      script: ./.travis/run_job.py recorder
    - name: transformer_miro
      script: ./.travis/run_job.py transformer_miro
    - name: transformer_sierra
      script: ./.travis/run_job.py transformer_sierra
    - name: transformer_mets
      script: ./.travis/run_job.py transformer_mets
    - name: transformer_calm
      script: ./.travis/run_job.py transformer_calm
    - name: sierra_reader
      script: ./.travis/run_job.py sierra_reader
    - name: sierra_bib_merger
      script: ./.travis/run_job.py sierra_bib_merger
    - name: sierra_item_merger
      script: ./.travis/run_job.py sierra_item_merger
    - name: sierra_items_to_dynamo
      script: ./.travis/run_job.py sierra_items_to_dynamo
    - name: mets_adapter
      script: ./.travis/run_job.py mets_adapter
    - name: calm_adapter
      script: ./.travis/run_job.py calm_adapter
    - name: inferrer
      script:
        - ./.travis/run_job.py inference_manager
        - ./.travis/run_job.py feature_inferrer --changes-in pipeline/inferrer/feature_inferrer
    - name: snapshot_generator
      script: ./.travis/run_job.py snapshot_generator
    - name: lambda-test
      env: TASK=lambda-test

script:
  - ./.travis/run_job.py

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - project/target
    - target

    - api/api/target

    - common/display/target
    - common/elasticsearch/target
    - common/elasticsearch_typesafe/target
    - common/internal_model/target

    - pipeline/id_minter/target
    - pipeline/ingestor/ingestor_common/target
    - pipeline/ingestor/ingestor_works/target
    - pipeline/ingestor/ingestor_images/target
    - pipeline/inferrer/inference_manager/target
    - pipeline/matcher/target
    - pipeline/merger/target
    - pipeline/recorder/target
    - pipeline/transformer/transformer_common/target
    - pipeline/transformer/transformer_miro/target
    - pipeline/transformer/transformer_sierra/target
    - pipeline/transformer/transformer_mets/target
    - pipeline/transformer/transformer_calm/target

    - reindexer/reindex_worker/target

    - sierra_adapter/common/target
    - sierra_adapter/sierra_reader/target
    - sierra_adapter/sierra_bib_merger/target
    - sierra_adapter/sierra_item_merger/target
    - sierra_adapter/sierra_items_to_dynamo/target

    - mets_adapter/mets_adapter/target
    - calm_adapter/calm_adapter/target

    - snapshots/snapshot_generator/target

stages:
  - preflight
  - libraries
  - services

before_install:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in secrets.zip.enc -out secrets.zip -d
  - unzip secrets.zip
  - chmod 600 id_rsa
  # Print the fingerprint of the SSH key, so we can check it's the same as the
  # deploy key in GitHub.
  - ssh-keygen -lf id_rsa
  - mkdir -p ~/.aws
  - cp config ~/.aws/config
  - cp credentials ~/.aws/credentials

install:
  # We need this for the Elasticsearch Docker container to start
  # See https://github.com/travis-ci/travis-ci/issues/6534
  - sudo sysctl -w vm.max_map_count=262144


services:
  - docker

dist: bionic

language: python
python: "3.7"

branches:
  only:
    - master

# Based on instructions from
# https://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#Caching
before_cache:
  - sudo find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - sudo find $HOME/.sbt        -name "*.lock"               -print -delete

env:
  global:
    - AWS_ECR_REPO=760097843905.dkr.ecr.eu-west-1.amazonaws.com

    # This forces Python to print everything to stdout/stderr immediately.
    # Otherwise, we've seen issues where all the output from our Travis scripts
    # gets buffered, and only gets printed at the end of the test...
    #
    # ... out of order from the rest of the rest of the output!
    #
    # See also: https://docs.python.org/3/using/cmdline.html#cmdoption-u
    #
    - PYTHONUNBUFFERED=x
