sns:
  image: wellcome/fake-sns
  ports:
    - "9292:9292"
sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"
sts:
  image: localstack/localstack
  ports:
    - "4592:4592"
    - "4572:4572"
  environment:
    - SERVICES=sts,s3
    - DEBUG=1
s3:
  image: scality/s3server:mem-latest
  ports:
    - "33333:8000"
