sns:
  image: wellcome/fake-sns
  ports:
    - "9292:9292"
sqs:
  image: s12v/elasticmq
  ports:
    - "9324:9324"
sts:
  image: motoserver/moto:1.3.5
  ports:
    - "5000:5000"
s3:
  image: scality/s3server:mem-latest
  ports:
    - "33333:8000"
